const state = {
  view:'dashboard', wizardStep:0,
  orderDraft:{customer:null,garment:null,measureMode:'existing',styles:[],staff:'Mahesh',trial:'2026-10-05',delivery:'2026-10-08',qty:1,price:1800,discount:0,advance:800,notes:''},
  customers:[
    {id:1,name:'Rahul Patil',phone:'9876543210',city:'Hubballi',orders:5,last:'21 Sep 2026'},
    {id:2,name:'Amit Jain',phone:'9845011223',city:'Dharwad',orders:3,last:'28 Sep 2026'},
    {id:3,name:'Sandeep Shah',phone:'9900112233',city:'Hubballi',orders:8,last:'01 Oct 2026'},
    {id:4,name:'Prakash Kulkarni',phone:'9988776655',city:'Hubballi',orders:1,last:'30 Sep 2026'}
  ],
  orders:[
    {no:'T7521',customer:'Rahul Patil',items:'Shirt ×2',delivery:'02 Oct',status:'Ready',staff:'Ramesh',amount:'₹3,600'},
    {no:'T7520',customer:'Amit Jain',items:'Pant ×2',delivery:'02 Oct',status:'Trial',staff:'Mahesh',amount:'₹2,800'},
    {no:'T7519',customer:'Sandeep Shah',items:'Suit ×1',delivery:'03 Oct',status:'Stitching',staff:'Mahesh',amount:'₹8,500'},
    {no:'T7518',customer:'Prakash Kulkarni',items:'Kurta ×2',delivery:'03 Oct',status:'Cutting',staff:'Ramesh',amount:'₹4,000'},
    {no:'T7517',customer:'Nitin Mehta',items:'Shirt ×3',delivery:'01 Oct',status:'Overdue',staff:'Vijay',amount:'₹5,400'},
    {no:'T7516',customer:'Kiran Rao',items:'Pant ×1',delivery:'04 Oct',status:'Stitching',staff:'Vijay',amount:'₹1,500'},
    {no:'T7515',customer:'Manoj Shetty',items:'Blazer ×1',delivery:'05 Oct',status:'Trial',staff:'Mahesh',amount:'₹6,800'},
    {no:'T7514',customer:'Ravi Hegde',items:'Kurta ×1',delivery:'06 Oct',status:'Cutting',staff:'Ramesh',amount:'₹2,000'}
  ],
  staff:[
    {name:'Ramesh',role:'Master Cutter',phone:'9845001122',pending:6,today:2},
    {name:'Mahesh',role:'Tailor',phone:'9845003344',pending:8,today:3},
    {name:'Vijay',role:'Tailor',phone:'9845005566',pending:5,today:2},
    {name:'Suresh',role:'Finishing',phone:'9845007788',pending:4,today:1}
  ]
};

const viewMeta={
 dashboard:['Dashboard',"Overview of today's tailoring operations"], orders:['Orders','Manage, search and track customer orders'],customers:['Customers','Customer profiles, order history and contact details'],measurements:['Measurements','Saved measurement profiles for repeat orders'],production:['Production','Track every order from cutting to delivery'],products:['Products & Styles','Manage garments and their available style options'],staff:['Staff','Team members, roles and active work queues'],reports:['Reports','Business, order and production insights'],settings:['Settings','Store and system configuration']
};
const $=s=>document.querySelector(s); const content=$('#content');
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
function statusClass(s){return s.toLowerCase()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

function setView(view){state.view=view;state.wizardStep=0;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const [t,s]=viewMeta[view]||['',''];$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;render()}
document.addEventListener('click',e=>{
  const nav=e.target.closest('[data-view]'); if(nav){setView(nav.dataset.view);return}
  if(e.target.closest('[data-action="new-order"]')){openWizard();return}
  const act=e.target.closest('[data-action]'); if(!act)return;
  const a=act.dataset.action;
  if(a==='wizard-next') nextWizard(); if(a==='wizard-back') backWizard(); if(a==='wizard-cancel') setView('orders');
  if(a==='select-customer'){state.orderDraft.customer=state.customers.find(c=>c.id==act.dataset.id);renderWizard()}
  if(a==='select-garment'){state.orderDraft.garment=act.dataset.garment;renderWizard()}
  if(a==='select-style'){const v=act.dataset.style;state.orderDraft.styles.includes(v)?state.orderDraft.styles=state.orderDraft.styles.filter(x=>x!==v):state.orderDraft.styles.push(v);renderWizard()}
  if(a==='add-customer') showAddCustomer();
  if(a==='save-customer') saveCustomer();
});

document.addEventListener('input',e=>{
  if(e.target.id==='customerSearch') filterCustomers(e.target.value);
  if(e.target.dataset.bind){state.orderDraft[e.target.dataset.bind]=e.target.type==='number'?Number(e.target.value):e.target.value}
});

document.addEventListener('change',e=>{if(e.target.dataset.bind){state.orderDraft[e.target.dataset.bind]=e.target.type==='number'?Number(e.target.value):e.target.value}});

function render(){if(state.view==='wizard')return renderWizard(); const map={dashboard:dashboard,orders:orders,customers,measurements,production,products,staff,reports,settings};content.innerHTML=(map[state.view]||dashboard)()}

function dashboard(){return `
<div class="grid stats">
${[['Today Orders','12','+3 vs yesterday'],['Trials Today','5','2 after 4 PM'],['Deliveries Today','7','1 pending payment'],['Pending Orders','28','Across all stages'],['Overdue','3','Needs attention'],['Balance Due','₹24,600','9 customers']].map(x=>`<div class="stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="hint">${x[2]}</div></div>`).join('')}
</div>
<div class="grid dashboard-main">
  <div class="panel"><div class="panel-head"><div><div class="panel-title">Today's Work</div><div class="panel-sub">Orders that need attention today</div></div><button class="ghost" data-view="orders">View all →</button></div><div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Item</th><th>Status</th><th>Staff</th><th>Delivery</th></tr></thead><tbody>${state.orders.slice(0,6).map(o=>orderRow(o,false)).join('')}</tbody></table></div></div>
  <div class="grid" style="gap:16px"><div class="panel"><div class="panel-head"><div><div class="panel-title">Due Today</div><div class="panel-sub">Trials and deliveries</div></div></div><div class="panel-body due-list">
  ${[['T7521','Rahul Patil','Delivery • Shirt ×2','11:00 AM'],['T7520','Amit Jain','Trial • Pant ×2','1:30 PM'],['T7517','Nitin Mehta','Overdue delivery • Shirt ×3','Urgent']].map(x=>`<div class="due-item"><div><strong>${x[0]} · ${x[1]}</strong><div class="meta">${x[2]}</div></div><div class="due-time">${x[3]}</div></div>`).join('')}
  </div></div><div class="panel"><div class="panel-head"><div class="panel-title">Quick Actions</div></div><div class="panel-body quick-actions"><button class="quick-card" data-action="new-order"><strong>+ New Order</strong><span>Start a guided order</span></button><button class="quick-card" data-view="customers"><strong>Find Customer</strong><span>Search by mobile/name</span></button><button class="quick-card" data-view="production"><strong>Production Board</strong><span>See work queues</span></button><button class="quick-card" data-view="measurements"><strong>Measurements</strong><span>Saved profiles</span></button></div></div></div>
</div>`}

function orderRow(o,actions=true){return `<tr><td><strong>${o.no}</strong></td><td>${o.customer}</td><td>${o.items}</td><td><span class="status ${statusClass(o.status)}">${o.status}</span></td><td>${o.staff}</td><td>${o.delivery}</td>${actions?`<td>${o.amount}</td><td><div class="row-actions"><button>View</button><button data-action="duplicate">Duplicate</button></div></td>`:''}</tr>`}
function orders(){return `<div class="toolbar"><div class="search">⌕ <input id="orderSearch" placeholder="Search order no, customer or phone"></div><div class="filters"><select><option>All Status</option><option>Cutting</option><option>Stitching</option><option>Trial</option><option>Ready</option></select><select><option>All Staff</option>${state.staff.map(s=>`<option>${s.name}</option>`).join('')}</select><button class="primary" data-action="new-order">+ New Order</button></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Status</th><th>Staff</th><th>Delivery</th><th>Amount</th><th>Actions</th></tr></thead><tbody>${state.orders.map(o=>orderRow(o)).join('')}</tbody></table></div></div>`}
function customers(){return `<div class="toolbar"><div class="search">⌕ <input placeholder="Search by customer name or mobile"></div><button class="primary" data-action="add-customer">+ Add Customer</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Mobile</th><th>City</th><th>Total Orders</th><th>Last Order</th><th>Actions</th></tr></thead><tbody>${state.customers.map(c=>`<tr><td><strong>${c.name}</strong></td><td>${c.phone}</td><td>${c.city}</td><td>${c.orders}</td><td>${c.last}</td><td><div class="row-actions"><button>View</button><button>Edit</button><button>New Order</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
function measurements(){return `<div class="toolbar"><div class="search">⌕ <input placeholder="Search customer measurements"></div><div class="filters"><select><option>All Garments</option><option>Shirt</option><option>Pant</option><option>Kurta</option></select></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Garment</th><th>Profile</th><th>Updated</th><th>Source Order</th><th>Actions</th></tr></thead><tbody>${[['Rahul Patil','Shirt','Regular Fit','21 Sep 2026','T7488'],['Amit Jain','Pant','Comfort Fit','28 Sep 2026','T7502'],['Sandeep Shah','Suit','Classic Fit','01 Oct 2026','T7519'],['Rahul Patil','Pant','Regular Fit','21 Sep 2026','T7488']].map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td><div class="row-actions"><button>View</button><button>Edit</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
function production(){const cols=['Cutting','Stitching','Trial','Ready','Delivered'];return `<div class="toolbar"><div><span class="muted small">Drag-and-drop is visual only in this frontend demo.</span></div><div class="filters"><select><option>All Staff</option>${state.staff.map(s=>`<option>${s.name}</option>`).join('')}</select><select><option>Today + Next 7 Days</option></select></div></div><div class="kanban">${cols.map(col=>`<div class="kanban-col"><div class="kanban-title"><span>${col}</span><span>${state.orders.filter(o=>o.status===col).length|| (col==='Delivered'?4:0)}</span></div>${state.orders.filter(o=>o.status===col).map(o=>`<div class="kanban-card"><strong>${o.no} · ${o.customer}</strong><div class="meta">${o.items}</div><span class="staff-pill">${o.staff}</span><div class="due">Due: ${o.delivery}</div><button class="ghost" data-action="move-stage" style="padding:7px 0 0">Move forward →</button></div>`).join('')||`<div class="empty small" style="padding:20px 5px">No active jobs</div>`}</div>`).join('')}</div>`}
function products(){const data=[['👔','Shirt','Top','12 style options'],['👖','Pant','Bottom','8 style options'],['🧥','Blazer','Top','10 style options'],['🥻','Kurta','Top','9 style options'],['🤵','Suit','Both','15 style options']];return `<div class="toolbar"><div class="search">⌕ <input placeholder="Search garments"></div><button class="primary">+ Add Product</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Type</th><th>Style Options</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.map(x=>`<tr><td><div class="style-row"><div class="thumb">${x[0]}</div><strong>${x[1]}</strong></div></td><td>${x[2]}</td><td>${x[3]}</td><td><span class="status ready">Active</span></td><td><div class="row-actions"><button>Manage Styles</button><button>Edit</button></div></td></tr>`).join('')}</tbody></table></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><div><div class="panel-title">Why styles live inside products</div><div class="panel-sub">Operators no longer need a separate “Link Patterns” module.</div></div></div><div class="panel-body small muted">Example: Shirt → Collar: Regular / Chinese / Spread · Sleeve: Full / Half · Pocket: Single / Double / No Pocket · Cuff: Standard / French. The options configured here automatically appear in New Order.</div></div>`}
function staff(){return `<div class="toolbar"><div class="search">⌕ <input placeholder="Search staff"></div><button class="primary">+ Add Staff</button></div><div class="grid" style="grid-template-columns:repeat(4,1fr)">${state.staff.map(s=>`<div class="panel"><div class="panel-body"><div style="display:flex;gap:10px;align-items:center"><div class="avatar" style="background:var(--green-bg);color:var(--olive)">${s.name.slice(0,2).toUpperCase()}</div><div><strong>${s.name}</strong><div class="small muted">${s.role}</div></div></div><div class="summary-row" style="margin-top:16px"><span>Pending jobs</span><strong>${s.pending}</strong></div><div class="summary-row"><span>Due today</span><strong>${s.today}</strong></div><div class="summary-row"><span>Phone</span><span>${s.phone}</span></div><button class="outline" style="width:100%;margin-top:10px">View Work Queue</button></div></div>`).join('')}</div>`}
function reports(){return `<div class="grid stats" style="grid-template-columns:repeat(4,1fr)">${[['Orders This Month','186','+14%'],['Revenue','₹3.82L','+9%'],['Avg Order Value','₹2,054','+4%'],['On-time Delivery','92%','+3%']].map(x=>`<div class="stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="hint">${x[2]} vs last month</div></div>`).join('')}</div><div class="grid" style="grid-template-columns:1fr 1fr;margin-top:16px"><div class="panel"><div class="panel-head"><div class="panel-title">Top Garments</div></div><div class="panel-body">${[['Shirt',74],['Pant',51],['Kurta',28],['Suit',18],['Blazer',15]].map(x=>`<div class="summary-row"><span>${x[0]}</span><strong>${x[1]} orders</strong></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><div class="panel-title">Production Health</div></div><div class="panel-body">${[['On time','92%'],['Late','5%'],['Alterations','3%'],['Avg turnaround','4.8 days']].map(x=>`<div class="summary-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></div></div>`}
function settings(){return `<div class="panel" style="max-width:720px"><div class="panel-head"><div><div class="panel-title">Store Settings</div><div class="panel-sub">Frontend placeholders ready for backend persistence</div></div></div><div class="panel-body"><div class="form-grid"><div class="field"><label>Store Name</label><input value="Tailors"></div><div class="field"><label>Phone</label><input value="+91 98765 43210"></div><div class="field"><label>Order Prefix</label><input value="T"></div><div class="field"><label>Default Delivery Days</label><input value="5" type="number"></div></div><div class="field" style="margin-top:15px"><label>Address</label><textarea>Hubballi, Karnataka</textarea></div><button class="primary" style="margin-top:14px">Save Settings</button></div></div>`}

function openWizard(){state.view='wizard';state.wizardStep=0;state.orderDraft={customer:null,garment:null,measureMode:'existing',styles:[],staff:'Mahesh',trial:'2026-10-05',delivery:'2026-10-08',qty:1,price:1800,discount:0,advance:800,notes:''};document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));$('#pageTitle').textContent='Create New Order';$('#pageSubtitle').textContent='Guided order creation';renderWizard()}
const steps=['Customer','Garment','Measurements','Style','Schedule','Payment','Review'];
function stepper(){return `<div class="stepper">${steps.map((s,i)=>`<div class="step ${i===state.wizardStep?'active':i<state.wizardStep?'done':''}"><div class="num">${i<state.wizardStep?'✓':i+1}</div><span>${s}</span></div>`).join('')}</div>`}
function renderWizard(){const body=[stepCustomer,stepGarment,stepMeasurements,stepStyles,stepSchedule,stepPayment,stepReview,stepSuccess][state.wizardStep]();content.innerHTML=`<div class="wizard-shell">${state.wizardStep<7?stepper():''}<div class="wizard-card">${body}</div></div>`}
function frame(title,sub,body,next='Continue'){return `<div class="wizard-head"><h2>${title}</h2><p>${sub}</p></div><div class="wizard-body">${body}</div><div class="wizard-foot"><button class="ghost" data-action="${state.wizardStep===0?'wizard-cancel':'wizard-back'}">${state.wizardStep===0?'Cancel':'← Back'}</button><button class="primary" data-action="wizard-next">${next} →</button></div>`}
function stepCustomer(){return frame('Select customer','Search existing customers by mobile number or name. Add a new customer without leaving the order.',`<div style="display:flex;gap:10px"><div class="search" style="flex:1"><span>⌕</span><input id="customerSearch" placeholder="Type customer name or mobile number"></div><button class="outline" data-action="add-customer">+ Add New Customer</button></div><div id="customerResults" class="customer-results">${customerCards(state.customers)}</div>`) }
function customerCards(list){return list.map(c=>`<div class="customer-card ${state.orderDraft.customer?.id===c.id?'selected':''}" data-action="select-customer" data-id="${c.id}"><div><div class="name">${c.name}</div><div class="meta">${c.phone} · ${c.city} · ${c.orders} previous orders</div></div><div class="small muted">${state.orderDraft.customer?.id===c.id?'Selected ✓':'Select →'}</div></div>`).join('')}
function filterCustomers(q){const v=q.toLowerCase();const list=state.customers.filter(c=>c.name.toLowerCase().includes(v)||c.phone.includes(v));$('#customerResults').innerHTML=list.length?customerCards(list):`<div class="empty">No customer found.<br><button class="primary" data-action="add-customer" style="margin-top:10px">+ Add New Customer</button></div>`}
function stepGarment(){const gs=[['Shirt','👔','From ₹1,800'],['Pant','👖','From ₹1,400'],['Kurta','🥻','From ₹2,000'],['Blazer','🧥','From ₹6,500'],['Suit','🤵','From ₹8,500'],['Other','✂','Custom garment']];return frame('Choose garment','Select what the customer is ordering. Style and measurement options will adapt automatically.',`<div class="choice-grid">${gs.map(g=>`<div class="choice-card ${state.orderDraft.garment===g[0]?'selected':''}" data-action="select-garment" data-garment="${g[0]}"><div class="emoji">${g[1]}</div><strong>${g[0]}</strong><small>${g[2]}</small></div>`).join('')}</div><div class="field" style="margin-top:17px;max-width:180px"><label>Quantity</label><input type="number" min="1" value="${state.orderDraft.qty}" data-bind="qty"></div>`) }
function stepMeasurements(){const m=state.orderDraft.garment||'Garment';const fields=m==='Pant'?['Waist','Seat','Thigh','Knee','Bottom','Outseam','Inseam']:['Chest','Waist','Shoulder','Sleeve','Length','Neck','Arm Hole'];return frame('Measurements',`Use ${state.orderDraft.customer?.name||'customer'}'s saved measurements or take fresh measurements.`,`<div class="choice-grid" style="grid-template-columns:1fr 1fr"><div class="choice-card ${state.orderDraft.measureMode==='existing'?'selected':''}" onclick="state.orderDraft.measureMode='existing';renderWizard()"><strong>Use previous measurement</strong><small>Last updated 21 Sep 2026</small></div><div class="choice-card ${state.orderDraft.measureMode==='new'?'selected':''}" onclick="state.orderDraft.measureMode='new';renderWizard()"><strong>Take new measurement</strong><small>Save as new profile for future orders</small></div></div><div class="section-label">${m} measurements (inches)</div><table class="measure-table"><tbody>${fields.map((f,i)=>`<tr><td>${f}</td><td><input value="${[40,36,18,24,29,15.5,19][i]||''}"></td><td class="small muted">${state.orderDraft.measureMode==='existing'?'Saved profile':'New value'}</td></tr>`).join('')}</tbody></table><div class="field" style="margin-top:14px"><label>Measurement Notes</label><textarea placeholder="e.g. Right shoulder slightly lower, prefers loose fit"></textarea></div>`) }
function stepStyles(){const options={Shirt:[['Fit','Slim','Regular','Comfort'],['Collar','Regular','Chinese','Spread'],['Sleeve','Full','Half'],['Pocket','Single','Double','No Pocket'],['Cuff','Standard','French']],Pant:[['Fit','Slim','Regular','Comfort'],['Pleat','Flat Front','Single Pleat','Double Pleat'],['Pocket','Side','Cross','No Back Pocket'],['Bottom','Regular','Narrow','Turn-up']],Kurta:[['Fit','Regular','Comfort'],['Collar','Mandarin','Round Neck','Open Collar'],['Sleeve','Full','3/4','Half'],['Pocket','Side','Chest','No Pocket']],Blazer:[['Fit','Slim','Regular'],['Lapel','Notch','Peak','Shawl'],['Button','One','Two','Three'],['Vent','Single','Double','No Vent']],Suit:[['Fit','Slim','Regular'],['Lapel','Notch','Peak'],['Vent','Single','Double'],['Trouser','Flat Front','Pleated']],Other:[['Style','Standard','Custom']]}[state.orderDraft.garment||'Shirt'];return frame('Style & design options','Only options configured for this garment are shown here.',options.map(group=>`<div class="section-label">${group[0]}</div><div class="chip-grid">${group.slice(1).map(x=>`<button class="chip ${state.orderDraft.styles.includes(x)?'selected':''}" data-action="select-style" data-style="${x}">${x}</button>`).join('')}</div>`).join(''))}
function stepSchedule(){return frame('Schedule & assign','Set trial/delivery dates and assign production responsibility.',`<div class="form-grid"><div class="field"><label>Trial Date</label><input type="date" value="${state.orderDraft.trial}" data-bind="trial"></div><div class="field"><label>Delivery Date</label><input type="date" value="${state.orderDraft.delivery}" data-bind="delivery"></div><div class="field"><label>Assign Tailor / Staff</label><select data-bind="staff">${state.staff.map(s=>`<option ${s.name===state.orderDraft.staff?'selected':''}>${s.name}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select><option>Normal</option><option>Urgent</option><option>VIP</option></select></div></div><div class="field" style="margin-top:15px"><label>Order Notes</label><textarea data-bind="notes" placeholder="Fabric details, special instructions, trial notes...">${state.orderDraft.notes}</textarea></div>`) }
function stepPayment(){const subtotal=state.orderDraft.price*state.orderDraft.qty;const total=subtotal-state.orderDraft.discount;const bal=total-state.orderDraft.advance;return frame('Pricing & payment','Record order value, discount and advance payment.',`<div class="form-grid three"><div class="field"><label>Unit Price</label><input type="number" value="${state.orderDraft.price}" data-bind="price"></div><div class="field"><label>Discount</label><input type="number" value="${state.orderDraft.discount}" data-bind="discount"></div><div class="field"><label>Advance Received</label><input type="number" value="${state.orderDraft.advance}" data-bind="advance"></div><div class="field"><label>Payment Method</label><select><option>UPI</option><option>Cash</option><option>Card</option><option>Bank Transfer</option></select></div></div><div class="summary-box" style="max-width:420px;margin-top:18px"><div class="summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="summary-row"><span>Discount</span><strong>-${money(state.orderDraft.discount)}</strong></div><div class="summary-row total-row"><span>Order Total</span><strong>${money(total)}</strong></div><div class="summary-row"><span>Advance</span><strong>${money(state.orderDraft.advance)}</strong></div><div class="summary-row"><span>Balance Due</span><strong style="color:var(--orange)">${money(bal)}</strong></div></div>`) }
function stepReview(){const d=state.orderDraft;const subtotal=d.price*d.qty,total=subtotal-d.discount,bal=total-d.advance;return frame('Review order','Confirm all details before creating the order.',`<div class="summary-grid"><div class="summary-box"><h4>Customer & Garment</h4><div class="summary-row"><span>Customer</span><strong>${d.customer?.name||'-'}</strong></div><div class="summary-row"><span>Mobile</span><span>${d.customer?.phone||'-'}</span></div><div class="summary-row"><span>Garment</span><strong>${d.garment||'-'} × ${d.qty}</strong></div><div class="summary-row"><span>Styles</span><span style="max-width:220px;text-align:right">${d.styles.join(', ')||'Standard'}</span></div></div><div class="summary-box"><h4>Schedule & Production</h4><div class="summary-row"><span>Trial</span><strong>${d.trial}</strong></div><div class="summary-row"><span>Delivery</span><strong>${d.delivery}</strong></div><div class="summary-row"><span>Assigned to</span><strong>${d.staff}</strong></div><div class="summary-row"><span>Starting stage</span><span class="status cutting">Cutting</span></div></div><div class="summary-box"><h4>Payment</h4><div class="summary-row"><span>Total</span><strong>${money(total)}</strong></div><div class="summary-row"><span>Advance</span><strong>${money(d.advance)}</strong></div><div class="summary-row total-row"><span>Balance</span><strong>${money(bal)}</strong></div></div><div class="summary-box"><h4>Measurements</h4><div class="summary-row"><span>Profile</span><strong>${d.measureMode==='existing'?'Previous measurement':'New measurement'}</strong></div><div class="small muted">Measurement values will be stored with this order and remain available for future repeat orders.</div></div></div>`, 'Create Order')}
function stepSuccess(){return `<div class="success-card"><div class="success-icon">✓</div><h2>Order T7522 Created</h2><p>The order has been added to the Cutting queue and the customer's balance is recorded.</p><div style="display:flex;justify-content:center;gap:9px;margin-top:20px;flex-wrap:wrap"><button class="outline" data-action="print">Print Receipt</button><button class="outline" data-action="whatsapp">WhatsApp Receipt</button><button class="secondary" onclick="setView('orders')">View Order</button><button class="primary" data-action="new-order">Create Another Order</button></div></div>`}
function nextWizard(){const s=state.wizardStep;if(s===0&&!state.orderDraft.customer)return toast('Select or add a customer to continue.');if(s===1&&!state.orderDraft.garment)return toast('Select a garment to continue.');if(s===6){state.orders.unshift({no:'T7522',customer:state.orderDraft.customer.name,items:`${state.orderDraft.garment} ×${state.orderDraft.qty}`,delivery:'08 Oct',status:'Cutting',staff:state.orderDraft.staff,amount:money(state.orderDraft.price*state.orderDraft.qty-state.orderDraft.discount)});$('#ordersBadge').textContent=state.orders.length;state.wizardStep=7;renderWizard();return}state.wizardStep=Math.min(7,s+1);renderWizard()}
function backWizard(){state.wizardStep=Math.max(0,state.wizardStep-1);renderWizard()}
function showAddCustomer(){$('#modalRoot').innerHTML=`<div style="position:fixed;inset:0;background:rgba(0,35,54,.45);display:grid;place-items:center;z-index:99;padding:20px" id="modalBackdrop"><div class="panel" style="width:min(520px,100%)"><div class="panel-head"><div><div class="panel-title">Add New Customer</div><div class="panel-sub">Customer will be selected automatically for this order.</div></div><button class="ghost" onclick="document.querySelector('#modalRoot').innerHTML=''">✕</button></div><div class="panel-body"><div class="form-grid"><div class="field"><label>Customer Name</label><input id="newCustName" placeholder="Full name"></div><div class="field"><label>Mobile Number</label><input id="newCustPhone" placeholder="10-digit mobile"></div><div class="field"><label>City</label><input id="newCustCity" value="Hubballi"></div><div class="field"><label>Alternate Number</label><input placeholder="Optional"></div></div><div class="field" style="margin-top:15px"><label>Address</label><textarea placeholder="Optional address"></textarea></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="outline" onclick="document.querySelector('#modalRoot').innerHTML=''">Cancel</button><button class="primary" data-action="save-customer">Save & Select Customer</button></div></div></div></div>`}
function saveCustomer(){const name=$('#newCustName').value.trim(),phone=$('#newCustPhone').value.trim(),city=$('#newCustCity').value.trim()||'Hubballi';if(!name||phone.length<10)return toast('Enter customer name and valid mobile number.');const c={id:Date.now(),name,phone,city,orders:0,last:'New'};state.customers.unshift(c);state.orderDraft.customer=c;$('#modalRoot').innerHTML='';toast('Customer added and selected.');if(state.view==='wizard')renderWizard();else render()}

render();