const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const listeners = {};
const element = () => ({innerHTML:'', textContent:'', dataset:{}, classList:{add(){},remove(){},toggle(){}},querySelectorAll(){return []},querySelector(){return {focus(){}}}});
const elements = {};
const context = vm.createContext({console, Date, Number, String, Object, Array, Set, JSON, Math, Blob, URL, setTimeout:()=>0,clearTimeout(){},localStorage:{getItem(){return null},setItem(){}},document:{body:element(),querySelector:s=>elements[s]??=element(),querySelectorAll:()=>[],addEventListener:(type,fn)=>(listeners[type]??=[]).push(fn)},window:{print(){}}});
for (const file of ['app.js','interactions.js']) vm.runInContext(fs.readFileSync(file,'utf8').replace(/initialiseApp\(\);\s*$/, ''),context);
const run = code => vm.runInContext(code,context);
async function click(id) {
  for (const fn of listeners.click) await fn({target:{classList:{contains:()=>false},closest:s=>s==='[data-action]'?{dataset:{action:'wizard-measurement-source',id}}:null}});
}
(async()=>{
  run(`state.customers=[{id:7,name:'Customer'}];state.products=[{id:9,name:'Shirt',price:100}];openWizard();state.orderDraft.customer=state.customers[0];state.orderDraft.garment='Shirt';state.wizardStep=1;
  calls=[];apiRequest=async (url,options)=>{calls.push({url,options});return [{id:42,customer_id:7,product_id:9,product_name:'Shirt',profile:'Regular',created_at:'2026-10-02',chest:40,waist:36}];};`);
  await run('nextWizard()');
  assert.equal(run('state.wizardStep'),2);
  assert.equal(run('calls[0].url'),'/api/customers/7/products/9/measurements');
  await click('previous');
  assert.match(run('stepMeasurements()'),/Regular/);
  assert.match(run('stepMeasurements()'),/2026-10-02/);
  await click('profile:42');
  assert.equal(run('state.orderDraft.measurementId'),42);
  assert.match(run('stepMeasurements()'),/Selected ?/);
  assert.match(run('stepMeasurements()'),/40/);
  assert.ok(!run('stepMeasurements()').includes('data-measure='));
  const count=run('calls.length');
  assert.equal(await run('saveWizardMeasurement()'),42);
  assert.equal(run('calls.length'),count,'previous measurement does not POST');
  await click('new');
  assert.equal(run('state.orderDraft.measurementId'),null);
  assert.match(run('stepMeasurements()'),/data-measure="Chest"/);
  run(`state.orderDraft.measurements={Chest:41};apiRequest=async(url,options)=>{calls.push({url,options});if(url==='/api/measurements')return {measurement:{id:99}};if(url==='/api/orders')return {order:{order_number:'T1'}};return [];};getSelectedPatternIds=async()=>[];loadOrdersFromBackend=async()=>{};loadMeasurementsFromBackend=async()=>{};loadCustomersFromBackend=async()=>{};`);
  await run('createWizardOrder()');
  const calls=run('calls');
  const measurement=calls.find(c=>c.url==='/api/measurements');
  const order=calls.find(c=>c.url==='/api/orders');
  assert.equal(JSON.parse(measurement.options.body).chest,41);
  assert.equal(JSON.parse(order.options.body).items[0].measurement_id,99);
  assert.ok(calls.indexOf(measurement)<calls.indexOf(order));
  run(`apiRequest=async url=>{if(url.includes('/products/')){const error=new Error('Not found');error.status=404;throw error;}return [{id:41,customer_id:7,product_id:9,created_at:'2026-10-01'},{id:42,customer_id:7,product_id:9,created_at:'2026-10-02'},{id:55,customer_id:7,product_id:10,created_at:'2026-10-03'}];};`);
  await run('loadWizardMeasurementProfiles()');
  assert.equal(run('state.orderDraft.measurementProfiles.length'),2);
  assert.equal(run('state.orderDraft.measurementProfiles[0].id'),42);
  assert.match(run('stepMeasurements()'),/Existing Measurements/);
  run(`state.orderDraft.measurementProfiles=[];state.orderDraft.measureMode='new';state.orderDraft.garment='Pant';`);
  assert.match(run('stepMeasurements()'),/Existing Measurements/);
  assert.match(run('stepMeasurements()'),/New Measurements/);
  assert.match(run('stepMeasurements()'),/data-measure="Inseam"/);
  await click('previous');
  assert.match(run('stepMeasurements()'),/No existing measurements found/);
  assert.ok(!run('stepMeasurements()').includes('data-measure='));
  await click('new');
  assert.match(run('stepMeasurements()'),/data-measure="Inseam"/);
  console.log('Passed: backend lookup, clickable profiles, saved preview, reuse without insert, new measurement before order, empty profiles and Pant fields.');
})().catch(error=>{console.error(error);process.exitCode=1;});
